// Regression tests for stats.js. Reference values come from SciPy
// (see test/reference.json, generated by test/make_reference.py).
const test = require("node:test");
const assert = require("node:assert/strict");
const S = require("../stats.js");
const { data: D, ref: R } = require("./reference.json");

const close = (actual, expected, tol, msg) =>
  assert.ok(Math.abs(actual - expected) <= tol, `${msg}: got ${actual}, expected ${expected} (±${tol})`);

test("parseNum is strict", () => {
  assert.equal(S.parseNum("1.5"), 1.5);
  assert.equal(S.parseNum(" -2e3 "), -2000);
  assert.equal(S.parseNum("1,234.5"), 1234.5);
  assert.equal(S.parseNum("−3"), -3);            // U+2212 minus
  assert.ok(Number.isNaN(S.parseNum("1,5")));     // decimal comma: ambiguous → rejected
  assert.ok(Number.isNaN(S.parseNum("0x1A")));
  assert.ok(Number.isNaN(S.parseNum("12abc")));
  assert.ok(Number.isNaN(S.parseNum("")));
});

test("parseDelimited picks one delimiter and honours quotes", () => {
  assert.deepEqual(S.parseDelimited("a\tb\n1,234\t5\n"), [["a", "b"], ["1,234", "5"]]);
  assert.deepEqual(S.parseDelimited("a;b\r\n1,5;2"), [["a", "b"], ["1,5", "2"]]);
  assert.deepEqual(S.parseDelimited('"Drug, A",B\n1,2'), [["Drug, A", "B"], ["1", "2"]]);
});

test("t-tests", () => {
  close(S.tTest(D.A, D.C, false).p, R.t_student, 1e-8, "Student");
  const w = S.tTest(D.A, D.C, true);
  close(w.p, R.t_welch, 1e-8, "Welch p");
  close(w.df, R.t_welch_df, 1e-8, "Welch df");
  close(S.pairedTTest(D.X, D.Y).p, R.paired, 1e-8, "paired");
});

test("Mann–Whitney U", () => {
  const ex = S.mannWhitney(D.E, D.F);
  assert.ok(ex.exact);
  close(ex.p, R.mwu_exact, 1e-10, "exact");
  close(S.mannWhitney(D.A, D.B).p, R.mwu_exact_sep, 1e-12, "exact, fully separated");
  const ties = S.mannWhitney(D.T1, D.T2);
  assert.ok(!ties.exact);
  close(ties.p, R.mwu_ties, 1e-8, "ties, normal approx");
  close(S.mannWhitney(D.L1, D.L2).p, R.mwu_large, 1e-8, "large n, normal approx");
});

test("Wilcoxon signed-rank", () => {
  const ex = S.wilcoxonSignedRank(D.Xe, D.Ye);
  assert.ok(ex.exact);
  close(ex.p, R.wsr_exact, 1e-10, "exact");
  close(ex.p, 0.0390625, 1e-10, "exact (R wilcox.test example)");
  // float differences that should tie (0.8, −0.2) must be detected as ties
  const ft = S.wilcoxonSignedRank(D.X, D.Y);
  assert.ok(!ft.exact);
  close(ft.p, R.wsr_approx_float_ties, 1e-8, "float ties, normal approx");
  close(S.wilcoxonSignedRank(D.Xt, D.Yt).p, R.wsr_ties, 1e-8, "ties, normal approx");
});

test("one-way ANOVA + post-hoc", () => {
  const av = S.anova([D.A, D.C, D.D]);
  close(av.p, R.anova, 1e-10, "ANOVA");
  const tk = S.anovaPosthoc(av, "tukey");
  tk.forEach((pr, i) => {
    close(pr.p, R.tukey_p[i], 2e-5, `Tukey p ${i}`);
    close(pr.ci[0], R.tukey_ci[i][0], 1e-4, `Tukey CI lo ${i}`);
    close(pr.ci[1], R.tukey_ci[i][1], 1e-4, `Tukey CI hi ${i}`);
  });
  // SciPy's Dunnett uses randomized quasi-Monte-Carlo integration → looser tolerance
  const dn = S.anovaPosthoc(av, "dunnett");
  dn.forEach((pr, i) => {
    close(pr.p, R.dunnett_p[i], 1e-3, `Dunnett p ${i}`);
    close(pr.ci[0], R.dunnett_ci[i][0], 2e-3, `Dunnett CI lo ${i}`);
    close(pr.ci[1], R.dunnett_ci[i][1], 2e-3, `Dunnett CI hi ${i}`);
  });
});

test("studentized range CDF", () => {
  R.ptukey.forEach(([q, k, df, p]) => close(S.ptukey(q, k, df), p, 2e-5, `ptukey(${q},${k},${df})`));
  close(S.qtukey(0.95, 3, 10), 3.877, 1e-3, "qtukey");
  // Dunnett two-sided 5% critical values, equal n (ρ = 0.5) — Dunnett (1955) tables
  close(S.qdunnett(0.95, [Math.SQRT1_2, Math.SQRT1_2], 10), 2.57, 6e-3, "qdunnett k=2 df=10");
  close(S.qdunnett(0.95, Array(4).fill(Math.SQRT1_2), 20), 2.65, 6e-3, "qdunnett k=4 df=20");
  close(S.qdunnett(0.95, [Math.SQRT1_2, Math.SQRT1_2], Infinity), 2.21, 6e-3, "qdunnett k=2 df=∞");
});

test("Holm / Bonferroni adjustment", () => {
  assert.deepEqual(S.adjustP([0.01, 0.04, 0.03], "bonferroni").map(p => +p.toFixed(10)), [0.03, 0.12, 0.09]);
  assert.deepEqual(S.adjustP([0.01, 0.04, 0.03], "holm").map(p => +p.toFixed(10)), [0.03, 0.06, 0.06]);
});

test("Kruskal–Wallis", () => {
  close(S.kruskalWallis([D.A, D.C, D.D]).p, R.kw, 1e-8, "KW");
  close(S.kruskalWallis([D.T1, D.T2, [3, 4, 5, 5, 6]]).p, R.kw_ties, 1e-8, "KW ties");
});

test("Shapiro–Wilk", () => {
  Object.entries(R.sw).forEach(([n, [W, p]]) => {
    const r = S.shapiroWilk(D.L1.slice(0, +n));
    close(r.W, W, 1e-4, `W n=${n}`);
    close(r.p, p, 2e-3, `p n=${n}`);
  });
  const b = S.shapiroWilk(D.B);
  close(b.W, R.sw_B[0], 1e-4, "W demo");
  assert.equal(S.shapiroWilk([1, 1, 1, 1]), null);
});

test("Brown–Forsythe", () => close(S.brownForsythe([D.A, D.C, D.D]).p, R.bf, 1e-8, "BF"));

test("compact letter display", () => {
  // Tukey: A–C and C–D significant, A–D not → C alone ('a', highest mean), A & D share 'b'
  const av = S.anova([D.A, D.C, D.D]);
  const letters = S.compactLetters(3, S.anovaPosthoc(av, "tukey"), av.desc.map(d => d.mean));
  assert.deepEqual(letters, ["b", "a", "b"]);
  // overlapping groups get two letters
  const pairs = [{ i: 0, j: 1, p: 0.5 }, { i: 1, j: 2, p: 0.5 }, { i: 0, j: 2, p: 0.01 }];
  assert.deepEqual(S.compactLetters(3, pairs, [3, 2, 1]), ["a", "ab", "b"]);
});

test("star thresholds", () => {
  assert.equal(S.starsFor(0.00005), "****");
  assert.equal(S.starsFor(0.0005), "***");
  assert.equal(S.starsFor(0.005), "**");
  assert.equal(S.starsFor(0.04), "*");
  assert.equal(S.starsFor(0.2), "ns");
});
